# https://raw.githubusercontent.com/obsidianmd/obsidian-developer-docs/main/en/Plugins/Releasing/Release%20your%20plugin%20with%20GitHub%20Actions.md
name: Release Obsidian plugin
on:
   push:
     tags:
       - "*" 

jobs:
     build:
       runs-on: ubuntu-latest

       steps:
         - uses: actions/checkout@v3

         - name: Use Node.js
           u